Repository JuliaStats/Clustering.jl, pull requests merged in 2020-03, with the labels that each got.

#185 kmeans corner cases for k=1 and k=n
  src/kmeans.jl
  test/kmeans.jl
  test/kmedoids.jl
Labels: enhancement

#186 rename kmedoids acost to cost re #98
  doc/source/kmedoids.md
  src/kmedoids.jl
  test/kmedoids.jl
Labels: api, enhancement

#187 Correct & expand k-medoids implementation note
  doc/source/kmedoids.md
  src/kmedoids.jl
Labels: docs

#188 Cleanup deprecations
  Project.toml
  src/deprecate.jl
  src/kmedoids.jl
Labels: enhancement

#189 Fix Travis CI
  .travis.yml
Labels: testing

#192 Fix propertynames() methods
  Project.toml
  src/deprecate.jl
Labels: bug
